; 212018535, 50%
; 324007202, 50%
.ORIG X4384

Calculator:
ST R0,R0_Save_Calculator ; STORING THE VALUES OF THE REGISTERS AT THE START OF THE SUBROUTINE
ST R1,R1_Save_Calculator
ST R2,R2_Save_Calculator
ST R3,R3_Save_Calculator
ST R4,R4_Save_Calculator
ST R5,R5_Save_Calculator
ST R6,R6_Save_Calculator
ST R7,R7_Save_Calculator
LEA R0,Input_String1_Calculator ; PUTTING INTO R0 THE ADDRESS OF THE BEGINING OF THE Input_String1 
PUTS ; PRINTING THE STRING THAT EXIST INTO R0
GETC ; Reading an input from the user and put the ascii value of the input in R0
OUT ; PRINTING THE VALUE THAT EXIST INTO R0 ,NOT THE NUMBER BUT WHAT DOES IT MEAN IN ASCII
ADD R5,R0,#0 ; PUTTING INTO R5 R0+0(SAVING THE ASCII VALUE OF THE ARITHMETIC OPERATION INTO R5)
LD R0 Enter_Ascii_Calculator
OUT 
LD R0,R0_Save_Calculator ; PUTTING INTO R0 THE PREVIOUS VALUE(THE FIRST NUMBER) 

LD R3,Div_Ascii_Calculator ; PUTTING INTO R3 THE ASCII VALUE OF THE OPERATION "/",IN NEGATIVE TO HELP US TO CHECK LATER
ADD R3,R3,R5 ; PUTTING INTO R3 R3+R5
BRnp Continue_Calculator ; IF THE RESULT IS NEGATIVE OR POSITIVE ,THEN THE USER DIDNT ENTERED "/", SO GO TO Continue
; ELSE THE USER ENTERED "/" THEN WE HAVE TO DO R0/R1 
LD R4,Div_Address_Calculator ; PUTTING INTO R4 Div_Address 
JSRR R4 ; GO TO THE ADDRESS THAT EXIST IN R4 AND PUT INTO R7 THE PC OF THE NEXT INSTRUCTION
BR Print_Calculator ; GO TO Print

Continue_Calculator
LD R3,Mul_Ascii_Calculator ; PUTTING INTO R3 THE ASCII VALUE OF THE OPERATION "*",IN NEGATIVE TO HELP US TO CHECK LATER
ADD R3,R3,R5 ; PUTTING INTO R3 R3+R5
BRnp Continue1_Calculator ; IF THE RESULT IS NEGATIVE OR POSITIVE ,THEN THE USER DIDNT ENTERED "*", SO GO TO Continue1
; ELSE THE USER ENTERED "*" THEN WE HAVE TO DO R0*R1
LD R4,Mul_Address_Calculator ; PUTTING INTO R4 Mul_Address
JSRR R4 ; GO TO THE ADDRESS THAT EXIST IN R4 AND PUT INTO R7 THE PC OF THE NEXT INSTRUCTION 
BR Print_Calculator ; GO TO Print

Continue1_Calculator
LD R3,Exp_Ascii_Calculator ; PUTTING INTO R3 THE ASCII VALUE OF THE OPERATION "^",IN NEGATIVE TO HELP US TO CHECK LATER
ADD R3,R3,R5 ; PUTTING INTO R3 R3+R5
BRnp Continue2_Calculator ; IF THE RESULT IS NEGATIVE OR POSITIVE ,THEN THE USER DIDNT ENTERED "^", SO GO TO Continue2
; ELSE THE USER ENTERED "^" THEN WE HAVE TO DO R0^R1
LD R4,EXP_Address_Calculator ; PUTTING INTO R4 EXP_Address
JSRR R4 ; GO TO THE ADDRESS THAT EXIST IN R4 AND PUT INTO R7 THE PC OF THE NEXT INSTRUCTION
BR Print_Calculator ; GO TO Print

Continue2_Calculator 
LD R3,Increase_Ascii_Calculator ; PUTTING INTO R3 THE ASCII VALUE OF THE OPERATION "+",IN NEGATIVE TO HELP US TO CHECK LATER
ADD R3,R3,R5 ; PUTTING INTO R3 R3+R5
BRnp Continue3_Calculator ; IF THE RESULT IS NEGATIVE OR POSITIVE ,THEN THE USER DIDNT ENTERED "+", SO GO TO Continue3
; ELSE THE USER ENTERED "+" THEN WE HAVE TO DO R0+R1
ADD R2,R0,R1 ; PUTTING INTO R2 R0+R1
BR Print_Calculator ; GO TO Print

Continue3_Calculator
; WE DIDNT CHECK THE INPUT HERE BECAUSE , WE SUPPOSE THAT THE INPUT IS CORRECT 
; IF THE USER DIDNT ENTERED "/","*","+","^" THEN THE INPUT SHOULD BE "-", SO WE HAVE TO DO R0+(-R1)
NOT R1,R1 ; TWOS COMPLIMENT TO R1 IT'S MEANS (R1*-1)
ADD R1,R1,#1
ADD R2,R0,R1 ; PUTTING INTO R2 R0+R1

Print_Calculator:
; PRINTING THE FIRST NUMBER THAT EXIST INTO R0
LD R4,PrintNum_Address_Calculator ; PUTTING INTO R4 PrintNum_Address
JSRR R4 ; GO TO THE ADDRESS THAT EXIST INTO R4 AND PUT INTO R7 THE PC OF THE NEXT INSTRUCTION
ADD R0,R5,#0 ; PUTTING INTO R0 R5+0 (THE ASCII VALUE OF THE ARITHMETIC OPERATION) 
OUT ; PRINTING THE VALUE THAT EXIST INTO R0 ,NOT THE NUMBER BUT WHAT DOES IT MEAN IN ASCII(THE ARITHMETIC OPERATION)
LD R0,R1_Save_Calculator ; PUTTING INTO R0 R1_Save_Calculator (THE SECOND NUMBER)
; PRINTING THE SECOND NUMBER THAT WE PUTTED IN R0 
JSRR R4 ; GO TO THE ADDRESS THAT EXIST INTO R4 AND PUT INTO R7 THE PC OF THE NEXT INSTRUCTION
LD R0,Equal_Ascii_Calculator ; PUTTING INTO R0 Equal_Ascii
OUT; PRINTING THE VALUE THAT EXIST INTO R0 ,NOT THE NUMBER BUT WHAT DOES IT MEAN IN ASCII(THE EQUAL SIGN)
ADD R0,R2,#0 ; PUTTING INTO R0 R2+0 (R2 INCLUDING THE FINAL RESULT OF THE ARITHMETIC OPERATION)
JSRR R4 ; GO TO THE ADDRESS THAT EXIST INTO R4 AND PUT INTO R7 THE PC OF THE NEXT INSTRUCTION
LD R0,R0_Save_Calculator ; LOADING THE START VALUES OF THE REGISTERS BEFORE ENTERRING THE Calculator SUBROUTINE 
LD R1,R1_Save_Calculator
LD R2,R2_Save_Calculator
LD R3,R3_Save_Calculator
LD R4,R4_Save_Calculator
LD R5,R5_Save_Calculator
LD R6,R6_Save_Calculator
LD R7,R7_Save_Calculator
RET

Equal_Ascii_Calculator .fill #61
PrintNum_Address_Calculator .fill X4320
Input_String1_Calculator .STRINGZ "Enter an arithmetic operation: "
Div_Address_Calculator .fill X4064
Mul_Address_Calculator .fill X4000
EXP_Address_Calculator .fill X40C8
Div_Ascii_Calculator .fill #-47
Mul_Ascii_Calculator .fill #-42
Increase_Ascii_Calculator .fill #-43
Decrease_Ascii_Calculator .fill #-45
Exp_Ascii_Calculator .fill #-94
R0_Save_Calculator .fill #0
R1_Save_Calculator .fill #0
R2_Save_Calculator .fill #0
R3_Save_Calculator .fill #0
R4_Save_Calculator .fill #0
R5_Save_Calculator .fill #0
R6_Save_Calculator .fill #0
R7_Save_Calculator .fill #0
Enter_Ascii_Calculator .fill #10
.END