; 212018535, 50%
; 324007202, 50%
.ORIG X40C8
Exp:
	ST R1,R1_SAVE_Exp 		; SAVE ALL THE REGISTERS WE WILL USE IN THE SUBROUTINE
	ST R0,R0_SAVE_Exp
	ST R4,R4_SAVE_Exp
	ST R7,R7_SAVE_Exp
	ST R3,R3_SAVE_Exp
	ST R5,R5_SAVE_Exp
	ST R6,R6_SAVE_Exp
     
	AND R2,R2,#0			; INITIALIZE R2
 
	ADD R1,R1,#0			; CHECK INVALID INPUT
	BRn INVALID_INPUT3_EXP
	ADD R0,R0,#0
	BRn INVALID_INPUT3_EXP
	ADD R1,R1,#0			; IF R1 <= 0 THEN YOU MUST TO CHECK IF R0 > 0
	BRnz CHECK_R0_EXP
	BR LOOPINIT_EXP		; IN CASE R1 > 0

CHECK_R0_EXP:
	ADD R0,R0,#0
	BRz INVALID_INPUT3_EXP
	ADD R2,R2,#1
	RET

LOOPINIT_EXP:
	ADD R3,R1,#0     		 ; R3 HOLDS R1 INPUT VALUE
	ADD R1,R0,#0 			 ; CHANGE R1 TO R0 INPUT VALUE
	ADD R4,R3,#-1     		 ; R4 IS COUNTER

LOOP_EXP:  					 ;  MULTIPLY R0, R1 TIMES
	ADD R4,R4,#0
	BRz UPDATE_EXP
        LD R6 MulAddress_EXP
        
	JSRR R6
	ADD R0,R2,#0
	ADD R4,R4,#-1
	BR LOOP_EXP


UPDATE_EXP:
	ADD R1,R3,#0
	ADD R2,R0,#0
	BR END_SUB3_EXP

INVALID_INPUT3_EXP:
	ADD R2,R2,#-1
	BR END_SUB3_EXP



END_SUB3_EXP:           			;RESTORE ALL THE REGISTERS VALUES
	LD R1,R1_SAVE_Exp
	LD R0,R0_SAVE_Exp
	LD R3,R3_SAVE_Exp
	LD R4,R4_SAVE_Exp
        LD R5,R5_SAVE_Exp
 	LD R6,R6_SAVE_Exp
        LD R7,R7_SAVE_Exp


RET

R1_SAVE_Exp .FILL #0
R0_SAVE_Exp .FILL #0
R3_SAVE_Exp .FILL #0
R4_SAVE_Exp .FILL #0
R5_SAVE_Exp .FILL #0
R7_SAVE_Exp .FILL #0
R6_SAVE_Exp .FILL #0
MulAddress_EXP .fill x4000
.END